### Invocar al servidor en mi maquina: localhost
GET http://localhost:3000/

### Obtener lista de tareas
GET http://localhost:3000/tasks

### Crear una nueva tarea
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Tarea 2",
    "detail": "Detalle de la tarea 2"
}

### req id test
GET http://localhost:3000/tasks/2

### editar tarea
PUT http://localhost:3000/tasks/2
Content-Type: application/json

{
    "title": "Tarea 2 MODIFICADA",
    "detail": "Detalle de la tarea 2 MODIFICADA"
}

### Eliminar tarea
DELETE http://localhost:3000/tasks/1

### Marcar completado
PUT http://localhost:3000/tasks/2?state=completed

### Marcar pendiente
PUT http://localhost:3000/tasks/2?state=pending